cd C:\capshiii\mobile\fitness_app
flutter run -d chrome --dart-define=SUPABASE_URL=https://itxetmemsztydtngaqjx.supabase.co --dart-define=SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0eGV0bWVtc3p0eWR0bmdhcWp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzNDI1NjYsImV4cCI6MjA5NTkxODU2Nn0.Cx75Lx4rMyYbhkAG43T2urYYpj4lEbvh2nkZLRWl9-E
